CREATE SCHEMA IF NOT EXISTS howvi;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE howvi.instituicao (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    telefone VARCHAR(20) NOT NULL
);

CREATE TABLE howvi.unidade_conservacao (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(200) NOT NULL,
    data_criacao DATE NOT NULL,
    descricao TEXT NOT NULL,
    imagem_url TEXT,
    id_instituicao UUID NOT NULL,
    CONSTRAINT fk_unidade_instituicao
        FOREIGN KEY (id_instituicao) REFERENCES howvi.instituicao(id)
);

CREATE TABLE howvi.municipio (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(100) NOT NULL,
    estado VARCHAR(2) NOT NULL
);

CREATE TABLE howvi.unidade_municipio (
    id_unidade UUID NOT NULL,
    id_municipio UUID NOT NULL,
    PRIMARY KEY (id_unidade, id_municipio),
    CONSTRAINT fk_unidade_municipio_unidade
        FOREIGN KEY (id_unidade) REFERENCES howvi.unidade_conservacao(id),
    CONSTRAINT fk_unidade_municipio_municipio
        FOREIGN KEY (id_municipio) REFERENCES howvi.municipio(id)
);

CREATE TABLE howvi.comunicacao (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo INT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(200) NOT NULL,
    descricao_detalhada TEXT NOT NULL,
    data_hora_envio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_comunicante TEXT NOT NULL,
    status INT NOT NULL DEFAULT 0,
    id_unidade UUID NOT NULL,
    CONSTRAINT ck_comunicacao_status CHECK (status IN (0, 1)),
    CONSTRAINT fk_comunicacao_unidade
        FOREIGN KEY (id_unidade) REFERENCES howvi.unidade_conservacao(id)
);

CREATE INDEX idx_unidade_conservacao_id_instituicao
ON howvi.unidade_conservacao (id_instituicao);

CREATE INDEX idx_unidade_conservacao_nome
ON howvi.unidade_conservacao (nome);

CREATE INDEX idx_municipio_nome_estado
ON howvi.municipio (nome, estado);

CREATE INDEX idx_unidade_municipio_id_municipio
ON howvi.unidade_municipio (id_municipio);

CREATE INDEX idx_comunicacao_id_unidade
ON howvi.comunicacao (id_unidade);

CREATE INDEX idx_comunicacao_id_unidade_data_hora
ON howvi.comunicacao (id_unidade, data_hora_envio DESC);

CREATE UNIQUE INDEX idx_comunicacao_codigo
ON howvi.comunicacao (codigo);
